task1:
	gcc -o 1a.o task1a.c
	gcc -o 1b.o task1b.c
	gcc -o 1c.o task1c.c

run1a:
	./1a.o
run1b:
	./1b.o
run1c:
	./1c.o
task2: 
	gcc -o p1.o task2_p1.c
	gcc -o p2.o task2_p2.c
	gcc -o p3.o task2_p3.c
runp1:
	./p1.o
runp2:
	./p2.o
runp3:
	./p3.o
clean:
	rm -rf *.o
