hello: 
	gcc -o hello_out.o todo_5_2.c
hello_out: 
	./hello_out.o

head: 
	gcc -o head_out.o todo_5_3.c
head_out: 
	./head_out.o helloworld.txt

cp: 
	gcc -o cp_out.o todo_5_4.c
cp_out: 
	./cp_out.o helloworld.txt new.txt

str:
	gcc -o str_out.o todo_6_1.c
str_out: 
	./str_out.o

process:
	gcc -o process_out.o todo_6_2.c
process_out: 
	./process_out.o

clean: 
	rm -f *.o

