mem:
	gcc mem.c -o mem.o
mem_out: mem
	./mem.o 10
va:
	gcc va.c -o va.o
va_out: va
	./va.o
add:
	gcc address.c -o add.o
add_out: add
	./add.o 5 6
corrupt:
	gcc corruptfunc.c -o corr.o
corrupt_out: corrupt
	./corr.o
int:
	gcc 1024ints.c -o int.o
int_out: int
	./int.o
clean: 
	rm -rf *.o
	
