fork: 
	gcc -o fork.o fork.c
run_fork: 
	./fork.o

exec: 
	gcc -o exec.o exec.c
run_exec: 
	./exec.o

ioredir: 
	gcc -o ioredir.o ioredir.c
run_ioredir: 
	./ioredir.o

wait: 
	gcc -o wait.o wait.c
run_wait: 
	./wait.o

task4: 
	gcc -o task4.o task2_4.c
run_4: 
	./task4.o

task6: 
	gcc -o task6.o task2_6.c
run_6: 
	./task6.o

fan: 
	gcc -o fan.o process_fan.c
run_fan: 
	./fan.o

chain: 
	gcc -o chain.o process_chain.c
run_chain: 
	./chain.o
	
clean: 
	rm -rf *.o